### ISSUE TITLE
Make Scrimmer ping work

### ISSUE THREAD

**Issue by PaulMndn** [jaimevisser/scrimbot#20]
### Currrently,
the bot creates a thread from nothing and writes in there. By doing so, however, it doesn't ping all Players with the Scrimmer role, but only the ones in the tread which at that point is nobody.

### Suggestion
Instead of creating a thread from nothing and writing in there, it would be better to send the initial message in the main channel and create a thread from that message. 
Reactions don't seem to get carried over into the tread, not sure how it is with buttons. On the other hand, it might not be that big of a deal if the buttons are only in the main channel and all further discussion happens in the thread.

**Comment by PaulMndn** [comment]
Great bot by the way. It gave me some ideas and inspirations for my own one. 🙂

**Comment by jaimevisser** [comment]
I'll have a look to see if I can make that work with pycord. Will need to do some testing to see how it responds to different API calls.

**Comment by jaimevisser** [comment]
Yeah, I'd need to add a second message to the thread for the buttons. Would still work though.

**Comment by jaimevisser** [comment]
So, the thing I'd like to do now is this:
Message 1) with @scrimmer, local time and counter (1/8) or maybe a big fat FULL if it's full.
Message 2) with the player list and join/reserve/leave buttons.

Message 1 will be in the scrim channel and will be the spawning point for the thread. The second message will live in the thread. Reason to keep the buttons and player list inside the thread is to encourage discussion to happen there.
