### ISSUE TITLE
/ActiveScrims (suggestion)

### ISSUE THREAD

**Issue by s-cag** [jaimevisser/scrimbot#33]
Allow a user to see the upcoming scrims in a embed message only the user can see to avoid clutter.

**Comment by jaimevisser** [comment]
Already have a list generated by the upcoming broadcasting functionality, this could probably reuse most of the same code.

**Comment by jaimevisser** [comment]
Related to #29

**Comment by jaimevisser** [comment]
Slash commands cannot have capital letters it seems. Will become /active-scrims
