### ISSUE TITLE
A way to set inviter (suggestion)

### ISSUE THREAD

**Issue by s-cag** [jaimevisser/scrimbot#34]
Add a button for people to be able to set themselves as inviter (first come first serve) which after pressed by someone will show the inviters name in place of the option to take the role of inviter.

**Comment by jaimevisser** [comment]
Would work best after #23 is implemented so the inviters' oculus profile could also be linked in the embed (or set as the embed URL even). Having an oculus profile set would be a requirement to be the inviter then.

**Comment by jaimevisser** [comment]
@s-cag is this still needed when scrimbot shows oculus links for all players on a scrim?

**Comment by jaimevisser** [comment]
Assuming it isn't. Closed.
