### ISSUE TITLE
A /TeamVmixed function (suggestion)

### ISSUE THREAD

**Issue by s-cag** [jaimevisser/scrimbot#36]
Allow people to start a team v mixed and use team roles to specify which team, e.g "Arena Wolves are looking for 4 @scrimmer for a Mixed V Team", if they dont have their team role just use dc name.

**Comment by jaimevisser** [comment]
Team roles aren't a thing on all servers where my bot runs. Might be ok for a user to just enter the team name in the command. 4-sized scrims shouldn't be too hard.

**Comment by jaimevisser** [comment]
Also related to #19

**Comment by jaimevisser** [comment]
@PaulMndn is working on this!
