### ISSUE TITLE
Auto join full scrim

### ISSUE THREAD

**Issue by Amitheninja** [jaimevisser/scrimbot#43]
When scrim is full and someone joins a dialog appears saying would you like to automatically join if a spot opens up? And two options yes no as buttons 
When and if a spot opens up scrimbot sends a message saying (reserved person name) has been automatically joined the scrim as (person who left) has left the scrim

**Comment by jaimevisser** [comment]
Instead of a yes/no dialog I added more helpful feedback when pressing reserve and the scrim is full. Simpler solution and it should at least make it clear to people how auto-join works.
