### ISSUE TITLE
Add a /pingall command in the thread for everyone in the scrim

### ISSUE THREAD

**Issue by StefoVR** [jaimevisser/scrimbot#45]

**Comment by jaimevisser** [comment]
Think we should also ping all reserves that have been previously called up?

**Comment by StefoVR** [comment]
I think don't ping reserves, because its mainly useful for stuff like asking for invite, asking to switch times to be earlier if a scrim fills quickly, etc

**Comment by jaimevisser** [comment]
Would @here not work in a thread?

**Comment by jaimevisser** [comment]
Depends on server settings I guess. Still worth building this in my opinion.
