### ISSUE TITLE
Not an issue just an idea for scrimmers who have a lot of time

### ISSUE THREAD

**Issue by Feendoge** [jaimevisser/scrimbot#6]
Being able to ask the bot to "touch grass" or something allows for a scrimmer to be pinged whenever a scrim nearly fills but doesn't. Say like 6/7 out of 8. Dunno of its any use

**Comment by jaimevisser** [comment]
Just to get it clear. Which one of these did you mean:

The scrim is at 6/7 out of 8, scrim time is now and then mention the scrimmer role for that channel hoping to get some extras.
or
The scrim is at 6/7 out of 8, 5-10 minutes before the scrim time call out with scrimmer role to hope to fill it.

**Comment by Feendoge** [comment]
The first one but honestly both work very similar

**Comment by jaimevisser** [comment]
Logic is going to be as follows: if the scrim can fill with 1-2 extra players + joined players + reserve the bot will also ping scrimmer when starting the match.
